- TV/MusicPlayerUI/MusicPlayerUI/MusicPlayerUI.TizenTV/MusicPlayerUI.TizenTV.csproj
- TV/MusicPlayerUI/MusicPlayerUI/MusicPlayerUI.TizenTV/tizen-manifest.xml
- TV/MusicPlayerUI/MusicPlayerUI/MusicPlayerUI/MusicPlayerUI.csproj
> [TV][MusicPlayerUI] Clean up

- Mobile/PlayerSample/PlayerSample/PlayerSample/Views/ListPage.xaml
fixed issue
Profile: Moblie
Jira: TNEXT-12712
[Sample_App][Tizen][PlayerSample] Text is overlap
> [PlayerSample] change properties to improve legibility of list

- Mobile/PlayerSample/PlayerSample/PlayerSample.Tizen.Mobile/PlayerSample.Tizen.Mobile.cs
- Mobile/PlayerSample/PlayerSample/PlayerSample.Tizen.Mobile/SecurityPort.cs
- Mobile/PlayerSample/PlayerSample/PlayerSample/Interfaces/IMediaPlayerSecurity.cs
- Mobile/PlayerSample/PlayerSample/PlayerSample/Models/SecurityProvider.cs
Profile: Moblie
add PrivacyPrivilegeManager to get permission
> [PlayerSample] add PrivacyPrivilegeManager to ask permission

- Mobile/Calendar/Calendar/Calendar/Views/MonthPage.xaml.cs
- Mobile/Contacts/Contacts/Contacts/Views/ListPage.xaml.cs
Signed-off-by: Sameer Prakash Pradhan <sp.pradhan@samsung.com>
> [Calendar][Sample App Update]

- Mobile/RecorderSample/RecorderSample/RecorderSample.Tizen.Mobile/RecorderSecurity.cs
- Mobile/RecorderSample/RecorderSample/RecorderSample/Interfaces/IRecorderSecurity.cs
- Mobile/RecorderSample/RecorderSample/RecorderSample/ViewModels/RecorderSecurityProvider.cs
Add code for checking required privileges.
> [RecorderSample] Add code for checking required privilege

- Mobile/RecorderSample/RecorderSample/RecorderSample.Tizen.Mobile/RecorderSecurity.cs
- Mobile/RecorderSample/RecorderSample/RecorderSample/Interfaces/IRecorderSecurity.cs
> [RecorderSample] Fix stylecop issues

- Mobile/PlayerSample/PlayerSample/PlayerSample/Interfaces/IMediaPlayerSecurity.cs
> [PlayerSample] fix code style

- Mobile/ImageUtilSample/ImageUtilSample/ImageUtilSample.Tizen.Mobile/ImageUtilSample.Tizen.Mobile.csproj
> [ImageUtilSample] Update Tizen.Net version

- Mobile/AudioManagerSample/AudioManagerSample/AudioManagerSample.Tizen.Mobile/AudioManagerController.cs
- Mobile/AudioManagerSample/AudioManagerSample/AudioManagerSample.Tizen.Mobile/AudioManagerSample.Tizen.Mobile.csproj
- Mobile/AudioManagerSample/AudioManagerSample/AudioManagerSample.Tizen.Mobile/tizen-manifest.xml
- Mobile/AudioManagerSample/AudioManagerSample/AudioManagerSample/AudioManagerSample.csproj
- Mobile/AudioManagerSample/AudioManagerSample/AudioManagerSample/Interfaces/DeviceRunningChangedEventArgs.cs
- Mobile/AudioManagerSample/AudioManagerSample/AudioManagerSample/Interfaces/IAudioManagerController.cs
- Mobile/AudioManagerSample/AudioManagerSample/AudioManagerSample/Models/DeviceItem.cs
- Mobile/AudioManagerSample/AudioManagerSample/AudioManagerSample/ViewModels/DeviceListPageViewModel.cs
- Mobile/AudioManagerSample/AudioManagerSample/AudioManagerSample/ViewModels/VolumePageViewModel.cs
- Mobile/AudioManagerSample/AudioManagerSample/AudioManagerSample/Views/DeviceListPage.xaml
- Mobile/AudioManagerSample/AudioManagerSample/AudioManagerSample/Views/MainPage.xaml
- Mobile/AudioManagerSample/AudioManagerSample/AudioManagerSample/Views/VolumePage.xaml
Represent device state by using AudioManager.DeviceRunningChanged which is API level 5
> [AudioManagerSample] Apply new device state API

- TV/ChannelList/ChannelList/src/view/ListAdapter.cs
> fix typo : 

- Mobile/SecureRepository/SecureRepository/SecureRepository/Views/MainPage.xaml
- Mobile/SecureRepository/SecureRepository/SecureRepository/Views/MainPage.xaml.cs
Signed-off-by: Ernest Borowski <e.borowski@partner.samsung.com>
> [SecureRepository][Mobile] Fix text allignment in listView

- Wearable/AmbientWatch/AmbientWatch/AmbientWatch.csproj
- Wearable/AppControl/AppControl/AppControl.csproj
- Wearable/AppControl/AppControl/tizen-manifest.xml
- Wearable/AppInformation/AppInformation/AppInformation.csproj
- Wearable/AppInformation/AppInformation/tizen-manifest.xml
- Wearable/ImageReader/ImageReader/ImageReader.csproj
- Wearable/ImageReader/ImageReader/tizen-manifest.xml
- Wearable/MessagePortSampleApp/MessagePortSampleApp/MessagePortSampleApp.csproj
- Wearable/MessagePortSampleApp/MessagePortSampleApp/tizen-manifest.xml
- Wearable/PlayingWithHWInputs/PlayingWithHWInputs/PlayingWithHWInputs.csproj
- Wearable/PlayingWithHWInputs/PlayingWithHWInputs/tizen-manifest.xml
- Wearable/SQLite.NET.Sample/SQLite.NET.Sample/SQLite.NET.Sample.csproj
- Wearable/SkiaSharp2DSample/SkiaSharp2DSample/SkiaSharp2DSample.csproj
- Wearable/SkiaSharp2DSample/SkiaSharp2DSample/tizen-manifest.xml
- Wearable/UsingResxLocalization/UsingResxLocalization/UsingResxLocalization.csproj
- Wearable/UsingResxLocalization/UsingResxLocalization/tizen-manifest.xml
- Wearable/VoiceMemo/VoiceMemo.Tizen.Wearable/tizen-manifest.xml
- Wearable/VoiceMemo/VoiceMemo/VoiceMemo.csproj
- Wearable/WeatherWatch/WeatherWatch/WeatherWatch.csproj
- Wearable/WeatherWatch/WeatherWatch/tizen-manifest.xml
- Wearable/WebWidgetHybrid/WebWidgetHybrid/WebWidgetHybrid.csproj
- Wearable/WebWidgetHybrid/WebWidgetHybrid/tizen-manifest.xml
- Wearable/XamarinFormsAndServiceApps/XamarinFormsAndServiceApps/XamarinFormsAndServiceApps.csproj
- Wearable/XamarinFormsAndServiceApps/XamarinFormsAndServiceApps/tizen-manifest.xml
Upgrade the version of Tizen.Wearable.CircularUI & Xamarin.Forms
> [Wearable] upgrade the version of Tizen.Wearable.CircularUI & Xamarin.Forms

- Wearable/PlayerSample/PlayerSample/ViewModels/InputUrlPageViewModel.cs
- Wearable/PlayerSample/PlayerSample/ViewModels/PlayPageViewModel.cs
1. fixed to check null string properly
2. added logs for debugging
> [PlayerSample] Fixed it to handle exception properly (SAD-502)

- Mobile/SecureRepository/README.md
- TV/SecureRepository/README.md
- Wearable/SecureRepository/README.md
Signed-off-by: Ernest Borowski <e.borowski@partner.samsung.com>
> [SecureRepository] Add information about layout limitations on Wearable

- Wearable/AmbientWatch/AmbientWatch/AmbientWatch.csproj
- Wearable/AnalogWatch/src/AnalogWatch/AnalogWatch.Tizen.Wearable/AnalogWatch.Tizen.Wearable.csproj
- Wearable/ChronographWatch/ChronographWatch/ChronographWatch.csproj
- Wearable/ClassicWatch/ClassicWatch/ClassicWatch.csproj
- Wearable/PhotoWatch/PhotoWatch/PhotoWatch.csproj
- Wearable/WeatherWatch/WeatherWatch/WeatherWatch.csproj
All the watch face projects will not compile either with VS Code or Visual Studio for Windows. I fixed the settings of the projects and now I can build and debug the projects.
Probably all the other projects need to be modified to be compatible with VS.
> Fix .csproj for WatchFace

- Mobile/Calculator/Calculator/tizen/Calculator/Calculator.Tizen/Calculator.Tizen.csproj
- Mobile/Calculator/Calculator/tizen/Calculator/Calculator/Calculator.csproj
Update Xamarin.Forms nuget for Calculator Mobile sample
> Update Xamarin.Forms nuget for Calculator Mobile sample

- Mobile/PlayerSample/PlayerSample/PlayerSample.Tizen.Mobile/MediaPlayer.cs
- Mobile/PlayerSample/PlayerSample/PlayerSample.Tizen.Mobile/PlayerSample.Tizen.Mobile.cs
- Mobile/PlayerSample/PlayerSample/PlayerSample.Tizen.Mobile/PlayerSample.Tizen.Mobile.csproj
- Mobile/PlayerSample/PlayerSample/PlayerSample.Tizen.Mobile/TransparentViewRenderer.cs
- Mobile/PlayerSample/PlayerSample/PlayerSample/Interfaces/IMediaPlayer.cs
- Mobile/PlayerSample/PlayerSample/PlayerSample/PlayerSample.csproj
- Mobile/PlayerSample/PlayerSample/PlayerSample/ViewModels/PlayPageViewModel.cs
- Mobile/PlayerSample/PlayerSample/PlayerSample/Views/PlayPage.xaml
- Mobile/PlayerSample/PlayerSample/PlayerSample/Views/TransparentView.cs
remove dependency with Tizen.Xamarin.Forms.Extension
> [MediaPlayer] remove dependency with extension library

- Mobile/Geofence/Geofence/Geofence/Geofence.csproj
- Mobile/Location/Location/Location/Location.csproj
Updated package for geofence and location  for issue TFDF-4738 
Signed-off-by: Susnata Sovalin <s.sovalin@samsung.com>
> Fix of TFDF-4738

- Mobile/IMESample/IMESample/IMESample/IMESample.cs
http://suprem.sec.samsung.net/jira/browse/SAD-660
> [Mobile][IMESample] Fix some keys blinking issue

- Mobile/Calendar/Calendar/Calendar/Calendar.csproj
- Mobile/PushReceiver/PushReceiver/PushReceiver.Tizen.Mobile/PushReceiver.Tizen.Mobile.csproj
- Mobile/SampleSync/SampleSync/SampleSync/SampleSync.csproj
Sample Apps crashed due to version mismatch of Xamarin.Forms
> Fix of Sample Apps Crash

- Mobile/Accounts/SampleAccount/SampleAccount.Tizen.Mobile/SampleAccount.Tizen.Mobile.csproj
- Mobile/Accounts/SampleAccount/SampleAccount/SampleAccount.csproj
- Mobile/AppHistory/AppHistory/AppHistory.Tizen.Mobile/AppHistory.Tizen.Mobile.csproj
- Mobile/AppHistory/AppHistory/AppHistory/AppHistory.csproj
Updating Xamarin Form version to avoid sample app crash issue.
> [MOBILE] Fixing Sample Crash Issue

- Mobile/Contacts/Contacts/Contacts.Tizen.Mobile/Contacts.Tizen.Mobile.cs
- Mobile/Contacts/Contacts/Contacts.Tizen.Mobile/Contacts.Tizen.Mobile.csproj
- Mobile/Contacts/Contacts/Contacts.Tizen.Mobile/tizen-manifest.xml
- Mobile/Contacts/Contacts/Contacts/Contacts.csproj
Signed-off-by: k.stepaniuk <k.stepaniuk@partner.samsung.com>
> [SAD-658] Xamarin upgrade

- Mobile/BasicCalculator/src/BasicCalculator/BasicCalculator/ViewModels/CalculatorViewModel.cs
- TV/BasicCalculator/src/BasicCalculator/BasicCalculator/ViewModels/CalculatorViewModel.cs
Fix unnecessary insertion of special key code into the calculator
> Fix BasicCalculator

- Mobile/SecureRepository/SecureRepository/SecureRepository.Tizen.Mobile/Constans.cs
- TV/SecureRepository/SecureRepository/SecureRepository.Tizen.TV/Constans.cs
- Wearable/SecureRepository/SecureRepository/SecureRepository.Tizen.Wearable/Constans.cs
Private keys embedded in code are reported by security analysis tools. Add a
comment explaining that these keys are only samples and their disclosure will
do no harm.
> [SecureRepository] Better description for private key samples

- TV/FlexContainerSample/FlexContainerSample/src/Devices.cs
- TV/FlexContainerSample/FlexContainerSample/src/FlexContainerSample.cs
FlexContainer  is deprecated in API8,   and will be removed in API10.  So use FlexLayout instead!
> [TV/FlexContainerSample] Replace FlexContainer by FlexLayout.

- TV/AnimationSample/AnimationSample/src/AnimationSample.cs
- TV/FlexContainerSample/FlexContainerSample/src/Devices.cs
- TV/FlexContainerSample/FlexContainerSample/src/FlexContainerSample.cs
ClickEvent is deprecated in API8,   and will be removed in API10.  So use Clicked instead!
> [TV/AnimationSample] Replace ClickEvent by Clicked.

- Mobile/NetworkApp/NetworkApp/NetworkApp.Tizen.Mobile/WiFiImplementation.cs
- Mobile/SmartCardSampleApp/SmartCardSampleApp/SmartCardSampleApp.Tizen.Mobile/SmartCardImplementation.cs
- Mobile/UI/ApplicationControl/ApplicationControl/ApplicationControl.Tizen.Mobile/Renderers/RadioButtonRenderer.cs
- Mobile/UI/Puzzle/Puzzle/Puzzle.Tizen.Mobile/Renderers/CustomImageButtonRenderer.cs
- Mobile/UI/Puzzle/Puzzle/Puzzle.Tizen.Mobile/Renderers/RadioButtonRenderer.cs
- TV/MediaHubSample/MediaHubSample/src/Common/EventCallback.cs
- TV/MediaHubSample/MediaHubSample/src/View/Dropdown.cs
- TV/MediaHubSample/MediaHubSample/src/View/ImageItem.cs
- TV/MediaHubSample/MediaHubSample/src/View/OptionList.cs
- Wearable/Compass/src/Compass/Compass/ViewModels/CompassViewModel.cs
- Wearable/ImageSample/ImageSample/ImageSample.cs
- Wearable/NetworkApp/NetworkApp/Views/NetworkListPage.xaml.cs
- Wearable/ReverseGeocoding/src/ReverseGeocoding/ReverseGeocoding.Tizen.Wearable/Renderers/TizenMapViewRenderer.cs
- Wearable/SmartCardSampleApp/SmartCardSampleApp/SmartCardSampleApp.Tizen.Wearable/SmartCardImplementation.cs
- Wearable/SquatCounter/src/SquatCounter/Services/PressureSensorService.cs
- Wearable/SquatCounter/src/SquatCounter/Services/SquatCounterService.cs
- Wearable/Ultraviolet/src/Ultraviolet/Ultraviolet/Ultraviolet.Tizen.Wearable/Services/UltravioletSensorService.cs
- Wearable/Ultraviolet/src/Ultraviolet/Ultraviolet/Ultraviolet/ViewModels/MainViewModel.cs
- Wearable/VisualsSample/VisualsSample/VisualsSample.cs
Needs to resolve Svace issues for C# Samples
1) Added null checker code to fix DEREF issues
Report for DEREF
https://code.sec.samsung.net/ahub/service/analyses/190676
https://code.sec.samsung.net/ahub/service/analyses/191290
Result for patch code
https://code.sec.samsung.net/ahub/service/analyses/191795
- Critical issues related with DEREF are removed.
> Addes checker code for DEREF_AFTER_NULL

- Wearable/Workout/src/Workout/App.xaml
- Wearable/Workout/src/Workout/Models/HeartRateMonitorModel.cs
- Wearable/Workout/src/Workout/Models/HomePageItemData.cs
- Wearable/Workout/src/Workout/Models/Workout/DetailsItemData.cs
- Wearable/Workout/src/Workout/Models/Workout/WorkoutModel.cs
- Wearable/Workout/src/Workout/Services/LocalTimeService.cs
- Wearable/Workout/src/Workout/Services/PageNavigationService.cs
- Wearable/Workout/src/Workout/ViewModels/HomePageViewModel.cs
- Wearable/Workout/src/Workout/ViewModels/Workout/DetailsPageViewModel.cs
- Wearable/Workout/src/Workout/Views/HomePageView.xaml
- Wearable/Workout/src/Workout/Views/HomePageView.xaml.cs
- Wearable/Workout/src/Workout/Views/PrivilegeDeniedPageView.xaml
- Wearable/Workout/src/Workout/Views/PrivilegeDeniedPageView.xaml.cs
- Wearable/Workout/src/Workout/Views/WelcomePageView.xaml
- Wearable/Workout/src/Workout/Views/WelcomePageView.xaml.cs
- Wearable/Workout/src/Workout/Views/Workout/CompletedPageView.xaml
- Wearable/Workout/src/Workout/Views/Workout/CompletedPageView.xaml.cs
- Wearable/Workout/src/Workout/Views/Workout/CountdownPageView.xaml
- Wearable/Workout/src/Workout/Views/Workout/CountdownPageView.xaml.cs
- Wearable/Workout/src/Workout/Views/Workout/DetailsPageView.xaml
- Wearable/Workout/src/Workout/Views/Workout/DetailsPageView.xaml.cs
- Wearable/Workout/src/Workout/Views/Workout/MainView.xaml
- Wearable/Workout/src/Workout/Views/Workout/MainView.xaml.cs
- Wearable/Workout/src/Workout/Views/Workout/PausePageView.xaml
- Wearable/Workout/src/Workout/Views/Workout/PausePageView.xaml.cs
- Wearable/Workout/src/Workout/Workout.cs
- Wearable/Workout/src/Workout/Workout.csproj
- Update to CircularUI 1.5
- Fixes after review
- ListView item source defined in xaml
- Updated size of the _bpmRangeOccurrences array
- Updated handler and event names
- Updated DetailsPageView code behind
> Update to CUI1.5 + code quality changes

- TV/FlexContainerSample/FlexContainerSample/src/FlexContainerSample.cs
- TV/ImageSample/ImageSample/src/Devices.cs
- TV/ImageSample/ImageSample/src/IExample.cs
- TV/ImageSample/ImageSample/src/ImageSample.cs
- TV/ImageSample/ImageSample/src/Program.cs
- TV/ImageSample/ImageSample/src/Samples/FittingModeSample.cs
- TV/ImageSample/ImageSample/src/Samples/GifSample.cs
- TV/ImageSample/ImageSample/src/Samples/MaskSample.cs
- TV/ImageSample/ImageSample/src/Samples/NinePatchSample.cs
- TV/ImageSample/ImageSample/src/Samples/PixelAreaSample.cs
- TV/ImageSample/ImageSample/src/Samples/SvgSample.cs
Main changes:
Remove unnecessary Using,
Remove useless commented line,
Replace "Position2D / Size2D" by "Position / Size",
Replace "ClickEvent" by "Clicked",
> [TV] Update ImageSample and FlexContainerSample.

- TV/AnimationSample/AnimationSample/src/AnimationSample.cs
This reverts commit e4891b88e4bce4ea34095cc6b174cc30e9d37256.
> Revert "[TV/AnimationSample] Replace ClickEvent by Clicked."

- TV/FlexContainerSample/FlexContainerSample/src/FlexContainerSample.cs
- TV/ImageSample/ImageSample/src/Devices.cs
- TV/ImageSample/ImageSample/src/IExample.cs
- TV/ImageSample/ImageSample/src/ImageSample.cs
- TV/ImageSample/ImageSample/src/Program.cs
- TV/ImageSample/ImageSample/src/Samples/FittingModeSample.cs
- TV/ImageSample/ImageSample/src/Samples/GifSample.cs
- TV/ImageSample/ImageSample/src/Samples/MaskSample.cs
- TV/ImageSample/ImageSample/src/Samples/NinePatchSample.cs
- TV/ImageSample/ImageSample/src/Samples/PixelAreaSample.cs
- TV/ImageSample/ImageSample/src/Samples/SvgSample.cs
This reverts commit b36e4a78cfc933838c94f01bb4d48ac95fd8aacc.
> Revert "[TV] Update ImageSample and FlexContainerSample."

- Mobile/Calculator/Calculator/tizen/Calculator/Calculator.Tizen/Calculator.Tizen.csproj
- Mobile/Calculator/Calculator/tizen/Calculator/Calculator.Tizen/tizen-manifest.xml
- Mobile/Calculator/Calculator/tizen/Calculator/Calculator/Calculator.csproj
Update Calculator sample for Tizen 6.0 release.
> [Mobile][Calculator] Update project settings by following Tizen 6.0

- Wearable/AnimationsSample/AnimationsSample/AnimationsSample.cs
Fixed Wearable\AnimationsSample.
View before:
View after:
> Fixed Wearable\AnimationsSample

- Wearable/MachineLearning/OrientationDetection/OrientationDetection/OrientationDetection.Tizen.Wearable/OrientationDetection.Tizen.Wearable.csproj
- Wearable/MachineLearning/OrientationDetection/OrientationDetection/OrientationDetection/OrientationDetection.cs
- Wearable/MachineLearning/OrientationDetection/OrientationDetection/OrientationDetection/OrientationDetection.csproj
- Target tizen 6.0
- Update Sdk and package versions
Signed-off-by: Yongjoo Ahn <yongjoo1.ahn@samsung.com>
> [Wearable/MachineLearning] Update package versions after tizen 6.0

- Wearable/AppHistory/AppHistory/AppHistory.cs
- Wearable/Badges/src/Badges/Badges.cs
- Wearable/Calculator/src/Calculator/Calculator.cs
- Wearable/FeedbackApp/src/FeedbackApp/FeedbackApp.cs
- Wearable/FindPlace/src/FindPlace/FindPlace.Tizen.Wearable/Behaviors/RotaryBehavior.cs
- Wearable/FindPlace/src/FindPlace/FindPlace.Tizen.Wearable/FindPlace.Tizen.Wearable.csproj
- Wearable/FindPlace/src/FindPlace/FindPlace.Tizen.Wearable/tizen-manifest.xml
- Wearable/HeartRateMonitor/src/HeartRateMonitor/HeartRateMonitor.cs
- Wearable/NFCSampleApp/NFCSampleApp/NFCSampleApp.cs
- Wearable/RotaryTimer/src/RotaryTimer/RotaryTimer.Tizen.Wearable/RotaryTimer.Tizen.Wearable.cs
- Wearable/SystemInfo/src/SystemInfo/SystemInfo.Tizen.Wearable/SystemInfo.Tizen.Wearable.cs
I upgraded version of Tizen in the FindPlace sample application. I applied changes which were required by this upgrade.
I also reverted CircularUI initialization according to comments from my last PR.
> [Wearable] Upgrade Tizen in FindPlace and revert initializing CircularUI

- Wearable/SQLite.NET.Sample/SQLite.NET.Sample/App.cs
- Wearable/SQLite.NET.Sample/SQLite.NET.Sample/SQLite.NET.Sample.cs
- Wearable/SQLite.NET.Sample/SQLite.NET.Sample/SQLite.NET.Sample.csproj
- Wearable/SQLite.NET.Sample/SQLite.NET.Sample/tizen-manifest.xml
- Use the latest version of SQLite related packages
- Remove the dependencies of Tizen.Wearable.CircularUI package
> Update SQLite sample app

- Wearable/PushReceiver/src/PushReceiver/PushReceiver.csproj
- Wearable/PushReceiver/src/PushReceiver/tizen-manifest.xml
Upgrade Tizen version in the wearable PushReceiver sample application.
> [Wearable] Upgrade Tizen version in the PushReceiver sample application

- Wearable/GestureSensor/README.md
- Wearable/GestureSensor/src/GestureSensor/GestureSensor/GestureSensor.Tizen.Wearable/GestureSensor.Tizen.Wearable.csproj
- Wearable/GestureSensor/src/GestureSensor/GestureSensor/GestureSensor.Tizen.Wearable/tizen-manifest.xml
- Wearable/GestureSensor/src/GestureSensor/GestureSensor/GestureSensor/GestureSensor.csproj
- Wearable/Lescanner/Lescanner/Lescanner.csproj
- Wearable/Lescanner/Lescanner/tizen-manifest.xml
- Wearable/Lescanner/README.md
I upgraded versions of Tizen and Xamarin.Forms in GestureSensor and Lescanner wearable sample apps. 
I also added information about target API level and tizen version of those apps.
> [Wearable] Tizen and Xamarin.Forms upgrade.

- Wearable/ImageSample/ImageSample/ImageSample.cs
Decrease buttons PointSize property
> [Wearable][ImageSample] Decrease buttons PointSize property

- TV/Xamarin.Forms/MusicPlayerUI/MusicPlayerUI/MusicPlayerUI/Behaviors/ButtonToModalNavigationBackEventBehavior.cs
- TV/Xamarin.Forms/MusicPlayerUI/MusicPlayerUI/MusicPlayerUI/Page/MenuPage.xaml
- TV/Xamarin.Forms/MusicPlayerUI/MusicPlayerUI/MusicPlayerUI/Page/ModalPlayPage.xaml
- TV/Xamarin.Forms/MusicPlayerUI/MusicPlayerUI/MusicPlayerUI/View/MusicBar.xaml
- Button => ImageButton
- Use ImageCell instead of StackLayout with Lable and Image
> Update application code for using Xamarin.Forms 5.0

- Mobile/NUI/VideoViewSample/VideoViewSample/VideoViewSample.cs
New comments ratio: 32.7%. Fixed StyleCop issues.
> [Mobile][NUI] Fixed VideoView Sample comments ratio and StyleCop issues.

- Mobile/NUI/CustomLayout/NUI_CustomLayout/ItemLayout.cs
Improved comments in ItemLayout.cs file.
> [Mobile][NUI][CustomLayout] Fixed comments ratio.

- Mobile/NUI/Layer/NUI_Layer/NUI_Layer.cs
> [Mobile][NUI][Layer] Fixed style issues and comments ratio.

- Mobile/Xamarin.Forms/UI/ApplicationControl/ApplicationControl/ApplicationControl.Tizen.Mobile/ApplicationOperations.cs
- Mobile/Xamarin.Forms/UI/ApplicationControl/ApplicationControl/ApplicationControl/MainPage.cs
- Wearable/Xamarin.Forms/Alarm/Alarm/Implements/AlarmPersistentHandler.cs
- Wearable/Xamarin.Forms/Alarm/Alarm/Renderers/ImageButtonRenderer.cs
- Wearable/Xamarin.Forms/Alarm/Alarm/Views/AlarmListCell.cs
- Wearable/Xamarin.Forms/ImageViewer/ImageViewer/Views/CircleContentViewRenderer.cs
Fixed svace issues the following apps.
- Mobile/Xamarin.Forms/UI/ApplicationControl
- Wearable/Xamarin.Forms/Alarm
- Wearable/Xamarin.Forms/ImageViewer
> [ApplicationControl][Alarm][ImageViewer] Fix svace issues

- Mobile/NUI/Pagination/NUI_Pagination/NUI_Pagination.cs
The touch event is handled together with the key event.
> [Mobile][NUI] Pagination - warnings cleanup

- Mobile/Xamarin.Forms/Calculator/Calculator/tizen/Calculator.sln
Fix cli build error by removing unit test of sample application.
> [Mobile][Calculator] Fix cli build error

- Mobile/Xamarin.Forms/Sensor/src/Sensor.sln
- Mobile/Xamarin.Forms/Sensor/src/Sensor/Sensor.Tizen.Mobile/Sensor.Tizen.Mobile.cs
- Mobile/Xamarin.Forms/Sensor/src/Sensor/Sensor.Tizen.Mobile/Sensor.Tizen.Mobile.csproj
- Mobile/Xamarin.Forms/Sensor/src/Sensor/Sensor.Tizen.Mobile/tizen-manifest.xml
- Mobile/Xamarin.Forms/Sensor/src/Sensor/Sensor/Sensor.cs
- Mobile/Xamarin.Forms/Sensor/src/Sensor/Sensor/Sensor.csproj
Signed-off-by: Yunmi Ha <yunmi.ha@samsung.com>
> [Mobile][Sensor] Change project file to latest version.

- Wearable/Xamarin.Forms/WeatherWatch/WeatherWatch/Services/ForecastService.cs
- Wearable/Xamarin.Forms/WebProxySample/src/WebProxySample/MainPageModel.cs
Fix Svace issues about the following apps.
Wearable/Xamarin.Forms/WeatherWatch
Wearable/Xamarin.Forms/WebProxySample
> Fix svace issues and remove unnecessary codes.

- Mobile/Xamarin.Forms/CalendarComponent/src/CalendarComponent/CalendarComponent.Tizen.Mobile/Renderers/CalendarViewRenderer.cs
- Mobile/Xamarin.Forms/SpeechToText/src/SpeechToText/SpeechToText/SpeechToText.xaml.cs
- Mobile/Xamarin.Forms/Weather/Weather/Weather/ViewModels/CurrentWeatherViewModel.cs
Fixed Svace defects of following Mobile Xamarin.Forms apps:
CalendarComponent
SpeechToText
Weather
> [Mobile][XF] Svace fixes.

- Wearable/Xamarin.Forms/Calculator/src/Calculator/Models/Operators.cs
- Wearable/Xamarin.Forms/Calculator/src/Calculator/Renderers/ImageButtonRenderer.cs
- Wearable/Xamarin.Forms/SpeechToText/SpeechToText/App.xaml.cs
- Wearable/Xamarin.Forms/TextReader/TextReader/Views/WearableViewResolver.cs
- Wearable/Xamarin.Forms/Weather/Weather/ViewModels/CurrentWeatherViewModel.cs
- Wearable/Xamarin.Forms/Weather/Weather/ViewModels/ForecastViewModel.cs
- Wearable/Xamarin.Forms/Workout/src/Workout/App.xaml.cs
- Wearable/Xamarin.Forms/Workout/src/Workout/Workout.csproj
Fixed Svace defects of following Wearable Xamarin.Forms apps:
1. SpeechToText
2. Calculator
3. NetworkApp
4. TextReader
5. Weather
> [Wearable][XF] Svace fixes.

- Mobile/NUI/Pagination/NUI_Pagination/NUI_Pagination.cs
- Mobile/NUI/ScrollableBaseExample/ScrollableBaseExample/ScrollableBaseExample.cs
- Mobile/NUI/VideoViewSample/VideoViewSample/VideoViewSample.cs
- Mobile/NUI/Visuals/NUI_Visuals/NUI_Visuals.cs
[NUI] Fix CodingStyle error and spellings
> [NUI] Fix CodingStyle error and spellings

- TV/NUI/ChannelList/ChannelList/src/Devices.cs
- TV/NUI/ChannelList/ChannelList/src/sample/ListData.cs
- TV/NUI/ChannelList/ChannelList/src/sample/ListItem.cs
- TV/NUI/ChannelList/ChannelList/src/view/List.cs
- TV/NUI/FirstScreen/FirstScreen/src/Devices.cs
- TV/NUI/FirstScreen/FirstScreen/src/MenuScreen.cs
- TV/NUI/FirstScreen/FirstScreen/src/SystemMenu.cs
- TV/NUI/MediaHubSample/MediaHubSample/src/Common/EventCallback.cs
- TV/NUI/MediaHubSample/MediaHubSample/src/Common/Ipage.cs
- TV/NUI/MediaHubSample/MediaHubSample/src/Common/ResourceData.cs
- TV/NUI/MediaHubSample/MediaHubSample/src/Devices.cs
- TV/NUI/MediaHubSample/MediaHubSample/src/Models/ContentModel.cs
- TV/NUI/MediaHubSample/MediaHubSample/src/View/Button.cs
- TV/NUI/MediaHubSample/MediaHubSample/src/View/Dropdown.cs
- TV/NUI/MediaHubSample/MediaHubSample/src/View/FootView.cs
- TV/NUI/MediaHubSample/MediaHubSample/src/View/GridListDataBridge.cs
- TV/NUI/MediaHubSample/MediaHubSample/src/View/GridView/Grid.cs
- TV/NUI/MediaHubSample/MediaHubSample/src/View/GridView/LinkerAnimation.cs
- TV/NUI/MediaHubSample/MediaHubSample/src/View/GridView/Rect.cs
- TV/NUI/MediaHubSample/MediaHubSample/src/View/ImageItem.cs
- TV/NUI/MediaHubSample/MediaHubSample/src/View/ListView/List.cs
- TV/NUI/MediaHubSample/MediaHubSample/src/View/OptionList.cs
- TV/NUI/MediaHubSample/MediaHubSample/src/View/TextItem.cs
- TV/NUI/MovieLibrary/MovieLibrary/MovieLibrary.cs
- TV/NUI/VisualSample/VisualSample/src/VisualSample.cs
[NUI] Fix TV's spelling and coding-style checker
> [NUI] Fix TV's spelling and coding-style checker

- Mobile/Xamarin.Forms/Accounts/SampleAccount/SampleAccount.Tizen.Mobile/SampleAccount.Tizen.Mobile.csproj
- Mobile/Xamarin.Forms/Accounts/SampleAccount/SampleAccount/SampleAccount.csproj
- Mobile/Xamarin.Forms/BasicCalculator/src/BasicCalculator/BasicCalculator.Tizen.Mobile/BasicCalculator.Tizen.Mobile.csproj
- Mobile/Xamarin.Forms/BasicCalculator/src/BasicCalculator/BasicCalculator/BasicCalculator.csproj
- Mobile/Xamarin.Forms/SecureRepository/SecureRepository/SecureRepository.Tizen.Mobile/SecureRepository.Tizen.Mobile.csproj
- Mobile/Xamarin.Forms/SecureRepository/SecureRepository/SecureRepository/SecureRepository.csproj
Update SDK and XF at following mobile sample apps:
- Accounts
- BasicCalculator
- SecureRepository
> [Mobile][XF] Upgrade csproj dependencies

- Mobile/Xamarin.Forms/Geofence/Geofence/Geofence.Tizen.Mobile/Geofence.Tizen.Mobile.csproj
- Mobile/Xamarin.Forms/Geofence/Geofence/Geofence/Geofence.csproj
Update project settings with latest Xamarin Form
> [Mobile][Geofence] Update project settings with latest Xamarin Form

- Mobile/Xamarin.Forms/NFCSampleApp/NFCSampleApp/NFCSampleApp.Tizen/NFCSampleApp.Tizen.csproj
- Mobile/Xamarin.Forms/NFCSampleApp/NFCSampleApp/NFCSampleApp/NFCSampleApp.csproj
- Mobile/Xamarin.Forms/SmartCardSampleApp/SmartCardSampleApp/SmartCardSampleApp.Tizen.Mobile/SmartCardSampleApp.Tizen.Mobile.csproj
- Mobile/Xamarin.Forms/SmartCardSampleApp/SmartCardSampleApp/SmartCardSampleApp/SmartCardSampleApp.csproj
Signed-off-by: jihoonjung <jh8801.jung@samsung.com>
> [Mobile][NFC/Smartcard] update Xamarin.Forms version

- Mobile/Xamarin.Forms/AudioIOSample/AudioIOSample/AudioIOSample/AudioIOSample.csproj
- Mobile/Xamarin.Forms/MediaContent/src/MediaContent/MediaContent/MediaContent.csproj
- Mobile/Xamarin.Forms/PlayerSample/PlayerSample/PlayerSample/PlayerSample.csproj
- Mobile/Xamarin.Forms/RadioSample/RadioSample/RadioSample/RadioSample.csproj
Update project settings with latest Xamarin Form
- AudioIO/MediaConent/Player/RadioSample
> [Mobile][AudioIO/MediaConent/Player/RadioSample] Fix Xamarin.Forms build warning

- Mobile/Xamarin.Forms/Camera/src/Camera/Camera.Tizen.Mobile/Camera.Tizen.Mobile.csproj
- Mobile/Xamarin.Forms/Camera/src/Camera/Camera/Camera.csproj
Plain and simple update of nuget version. The app works the same after update.
> [Mobile][Camera] Update Xamarin.Forms to 5.0

- Mobile/Xamarin.Forms/SystemInfo/src/SystemInfo/SystemInfo.Tizen.Mobile/Service/CapabilityService.cs
- Mobile/Xamarin.Forms/SystemInfo/src/SystemInfo/SystemInfo.Tizen.Mobile/tizen-manifest.xml
Add network.wifi feature check before accessing WiFi system settings, which causes errors when running in debug mode.
Add privilege for haptic.
> [Mobile/XF/SystemInfo] Fix run with debugging issue

- Mobile/NUI/CheckBox/NUI_CheckBox/NUI_CheckBox.cs
This patch fix NUI_Checkbox application crash.
> [NUI][Mobile] Checkbox - fix application crush

- Mobile/Xamarin.Forms/Calendar/Calendar/Calendar/ViewModels/MonthPageViewModel.cs
Signed-off-by: abhimanyu1dots <65957056+abhimanyu1dots@users.noreply.github.com>
> Calendar Sample App Crash Fix

- Mobile/NUI/Visuals/NUI_Visuals/NUI_Visuals.cs
The property shouldn't be used - hiden in the source code
> [NUI][Visuals] removed CornerRadius property

- Mobile/NUI/FlexLayout/NUIFlexLayout/NUIFlexLayout.cs
The size of Views inside Layout is calculated by Views'
Width/HeightSpecification instead of Width/HeightResizePolicy.
Therefore, some Width/HeightResizePolicy has been replaced with
Width/HeightSpecification.
> [NUI] Fix FlexLayout to calculate correct size

- Mobile/Xamarin.Forms/UI/AppCommon/AppCommon/AppCommon/ApplicationInformationViewModel.cs
- Mobile/Xamarin.Forms/UI/AppCommon/AppCommon/AppCommon/Cells/PathItemCell.cs
- Mobile/Xamarin.Forms/UI/AppCommon/AppCommon/AppCommon/PathsPageViewModel.cs
- Mobile/Xamarin.Forms/UI/AppCommon/AppCommon/AppCommon/Styles/ApplicationInformationStyle.cs
- change small fontsize in application and path label.
- fix crashing degree symbol issue
> [Xamarin.Forms][AppCommon]Fix small fontsize and crashed degree symbol

- Mobile/Xamarin.Forms/UI/ApplicationControl/ApplicationControl/ApplicationControl.Tizen.Mobile/Effects/BlendColorEffect.cs
- Mobile/Xamarin.Forms/UI/ApplicationControl/ApplicationControl/ApplicationControl/MainPage.cs
- Mobile/Xamarin.Forms/UI/ApplicationControl/ApplicationControl/ApplicationControl/OperationLayout.cs
- Fix exception when press `Execute` button with selecting empty app in View operation.
> Fix exception in view operation when excute button is pressed

- Mobile/Xamarin.Forms/Camera/README.md
- Mobile/Xamarin.Forms/Camera/src/Camera/Camera/View/PhotoPreviewPage.xaml
- Mobile/Xamarin.Forms/MachineLearning/TextClassification/TextClassification/TextClassification/Views/UserInput.xaml
In both cases the fonts has been enlarged by 60%
Related to issue SAD-914
> [Mobile/Camera+TextClassification] increase FontSize

- Mobile/Xamarin.Forms/MediaContent/src/MediaContent/MediaContent.Tizen.Mobile/Services/DatabaseManagerService.cs
Fix DB filter expression bug.
- SAD-913 issue
> [Mobile][MediaContent] Fix DB filter expression bug

- Mobile/Xamarin.Forms/Accounts/SampleAccount/SampleAccount/Views/AccountSignOut.xaml
Signed-off-by: Abhimanyu Swami/Application S/W Group /SRI-Delhi/Engineer/Samsung Electronics <abhimanyu1.s@samsung.com>
> Fix text size too small issue JIRA:SAD-918

- Mobile/NUI/VideoViewSample/VideoViewSample/VideoViewSample.cs
LinearLayout.Alignment -> LinearLayout.HorizontalAlignment or LinearLayout.VerticalAlignment
> [NUI][VideoViewSample] replace deprecated attribs

- Mobile/Xamarin.Forms/GoogleAPIExample/GoogleAPIExample/GoogleAPIExample.Tizen/GoogleAPIExample.Tizen.csproj
- Mobile/Xamarin.Forms/OAuthExample/OAuthExample/OAuthExample.Tizen/OAuthExample.Tizen.csproj
Fix csproj to use Tizen.NET.Sdk instead Microsoft.NET.Sdk
> Fix csproj on OAuthExample/GoogleAPIExample to use tizen sdk

- TV/OpenTK/Ball3D/Ball3D/Ball3D.csproj
- TV/OpenTK/CubeTexture/CubeTexture/CubeTexture.csproj
- TV/OpenTK/CubeWithSkiaSharp/CubeWithSkiaSharp/CubeWithSkiaSharp.csproj
- TV/OpenTK/Graffiti/Graffiti/Graffiti.csproj
- TV/OpenTK/Panorama360/Panorama360/Panorama360.csproj
- TV/OpenTK/ParticleDynamic/ParticleDynamic/ParticleDynamic.csproj
- TV/OpenTK/ScratchPaper/ScratchPaper/ScratchPaper.csproj
- TV/OpenTK/Star/Star/Star.csproj
- TV/OpenTK/Triangle/Triangle/Triangle.csproj
test target:
PontusM TV
csapi-tizenfx-tv-10.0.0.17353+nui22134-1.noarch
Samples                                                
**Ball3D**                              ：                         Pass
**CubeTexture**                     ：                         Pass
**CubeWithSkiaSharp**         ：                         _Fail               The TV target have no the library of SkiaSharp._
**Graffiti**                              ：                         Pass
**Panorama360**                   ：                        Pass
**ParticleDynamic**               ：                        Pass
**ScratchPaper**                    ：                         Pass
**Star**                                   ：                         Pass
**Triangle**                             ： …
> [TV][OpenTK] Fix build & warning errors of TV/OpenTK.

- TV/NUI/ChannelList/ChannelList/ChannelList.csproj
- TV/NUI/ChannelList/ChannelList/src/sample/ListData.cs
- TV/NUI/FirstScreen/FirstScreen/FirstScreen.csproj
- TV/NUI/FirstScreen/FirstScreen/src/MenuScreen.cs
- TV/NUI/FirstScreen/FirstScreen/src/ScrollMenu.cs
- TV/NUI/FirstScreen/FirstScreen/src/SourceMenu.cs
- TV/NUI/FirstScreen/FirstScreen/src/SystemMenu.cs
- TV/NUI/MediaHubSample/MediaHubSample/MediaHubSample.csproj
- TV/NUI/MediaHubSample/MediaHubSample/src/View/FootView.cs
- TV/NUI/MediaHubSample/MediaHubSample/src/View/HeadView.cs
- TV/NUI/MediaHubSample/MediaHubSample/src/View/ImageItem.cs
- TV/NUI/MovieLibrary/MovieLibrary/MovieLibrary.csproj
- TV/NUI/VisualSample/VisualSample/VisualSample.csproj
test target:
PontusM TV
csapi-tizenfx-tv-10.0.0.17353+nui22134-1.noarch
Samples
**ChannelList** ： Pass
**FirstScreen** ： The sample can launch normally, but it seems cannot response to the remote control.
**MediaHubSample** ： Pass
**MovieLibrary** ： Pass
**VisualSample** ： Pass
> [TV][NUI] Fix build & warning errors of TV/NUI.
